/* Delete the tables if they already exist */
drop table if exists stocks;
drop table if exists users;
drop table if exists limitbuy;
drop table if exists limitsell;

/* Create the schema for our tables */
CREATE TABLE stocks (name1 varchar(10), name2 nvarchar(80), price decimal(65,2));
/*CREATE TABLE users(firstname varchar(40), lastname varchar(40), username varchar(40), accountnumber char(4), password nvarchar(40), banktransaction nvarchar(100), balance decimal(5,2), personalstock nvarchar(100), stocktransaction nvarchar(100));*/
CREATE TABLE users(firstname varchar(40), lastname varchar(40), username varchar(40), password nvarchar(40),
 banktransaction nvarchar(100), personalstock nvarchar(100),
 stocktransaction nvarchar(100), balance decimal(65,2), accountnumber int(4) zerofill not null auto_increment,PRIMARY KEY (accountnumber));
CREATE TABLE limitbuy(stock varchar(40), shares int, price decimal(65,2), username varchar(40));
CREATE TABLE limitsell(stock varchar(40), shares int, price decimal(65,2), username varchar(40));

/* Populate the tables with our data */
INSERT INTO stocks VALUES ('AXP', 'American Express Co', null);
INSERT INTO stocks VALUES ('BA', 'Boeing Co', null);
INSERT INTO stocks VALUES ('CAT', 'Caterpillar Inc', null);
INSERT INTO stocks VALUES ('CVX', 'Chevron Corp', null);
INSERT INTO stocks VALUES ('DIS', 'Walt Disney Co', null);
INSERT INTO stocks VALUES ('DD', 'E I du Pont de Nemours and Co', null);
INSERT INTO stocks VALUES ('XOM', 'Exxon Mobil Corp', null);
INSERT INTO stocks VALUES ('GE', 'General Electric Co', null);
INSERT INTO stocks VALUES ('GS', 'Goldman Sachs Group Inc', null);
INSERT INTO stocks VALUES ('HD', 'Home Depot Inc', null);
INSERT INTO stocks VALUES ('IBM', 'International Business Machines Corp ', null);
INSERT INTO stocks VALUES ('JNJ', 'Johnson & Johnson', null);
INSERT INTO stocks VALUES ('JPM', 'JPMorgan Chase and Co', null);
INSERT INTO stocks VALUES ('KO', 'Coca-Cola Co', null);
INSERT INTO stocks VALUES ('MMM', '3M Co', null);
INSERT INTO stocks VALUES ('MCD', 'McDonald\'s Corp', null);
INSERT INTO stocks VALUES ('MRK', 'Merck & Co Inc', null);
INSERT INTO stocks VALUES ('NKE', 'Nike Inc', null);
INSERT INTO stocks VALUES ('PFE', 'Pfizer Inc', null);
INSERT INTO stocks VALUES ('PG', 'Procter & Gamble Co', null);
INSERT INTO stocks VALUES ('TRV', 'Travelers Companies Inc', null);
INSERT INTO stocks VALUES ('UTX', 'United Technologies Corp', null);
INSERT INTO stocks VALUES ('UNH', 'UnitedHealth Group Inc', null);
INSERT INTO stocks VALUES ('VZ', 'Verizon Communications Inc', null);
INSERT INTO stocks VALUES ('V', 'Visa Inc', null);
INSERT INTO stocks VALUES ('WMT', 'Wal Mart Stores Inc', null);
INSERT INTO stocks VALUES ('AAL', ' American Airlines Group Inc.', null);
INSERT INTO stocks VALUES ('AAPL', 'Apple Inc.', null);
INSERT INTO stocks VALUES ('ADBE', 'Adobe Systems Incorporated', null);
INSERT INTO stocks VALUES ('ADI', 'Analog Devices Inc.', null);
INSERT INTO stocks VALUES ('ADP', 'Automatic Data Processing Inc.', null);
INSERT INTO stocks VALUES ('ADSK', 'Autodesk Inc.', null);
INSERT INTO stocks VALUES ('AKAM', 'Akamai Technologies Inc.', null);
INSERT INTO stocks VALUES ('ALXN', 'Alexion Pharmaceuticals Inc.', null);
INSERT INTO stocks VALUES ('AMAT', 'Applied Materials Inc.', null);
INSERT INTO stocks VALUES ('AMGN', 'Amgen Inc.', null);
INSERT INTO stocks VALUES ('AMZN', 'Amazon.com Inc.', null);
INSERT INTO stocks VALUES ('ATVI', 'Activision Blizzard Inc', null);
INSERT INTO stocks VALUES ('AVGO', 'Avago Technologies Limited', null);
INSERT INTO stocks VALUES ('BBBY', 'Bed Bath & Beyond Inc.', null);
INSERT INTO stocks VALUES ('BIDU', 'Baidu Inc.', null);
INSERT INTO stocks VALUES ('BIIB', 'Biogen Inc.', null);
INSERT INTO stocks VALUES ('BMRN', 'BioMarin Pharmaceutical Inc.', null);
INSERT INTO stocks VALUES ('CA', 'CA Inc.', null);
INSERT INTO stocks VALUES ('CELG', 'Celgene Corporation', null);
INSERT INTO stocks VALUES ('CERN', 'Cerner Corporation', null);
INSERT INTO stocks VALUES ('CHKP', 'Check Point Software Technologies Ltd.', null);
INSERT INTO stocks VALUES ('CHRW', 'C.H. Robinson Worldwide Inc.', null);
INSERT INTO stocks VALUES ('CHTR', 'Charter Communications Inc.', null);
INSERT INTO stocks VALUES ('CMCSA', 'Comcast Corporation', null);
INSERT INTO stocks VALUES ('CMCSK', 'Comcast Corporation', null);
INSERT INTO stocks VALUES ('COST', 'Costco Wholesale Corporation', null);
INSERT INTO stocks VALUES ('CSCO', 'Cisco Systems Inc.', null);
INSERT INTO stocks VALUES ('CTSH', 'Cognizant Technology Solutions Corporation', null);
INSERT INTO stocks VALUES ('CTXS', 'Citrix Systems Inc.', null);
INSERT INTO stocks VALUES ('DISCA', 'Discovery Communications Inc.', null);
INSERT INTO stocks VALUES ('DISCK', 'Discovery Communications Inc.', null);
INSERT INTO stocks VALUES ('DISH', 'DISH Network Corporation', null);
INSERT INTO stocks VALUES ('DLTR', 'Dollar Tree Inc.', null);
INSERT INTO stocks VALUES ('EA', 'Electronic Arts Inc.', null);
INSERT INTO stocks VALUES ('EBAY', 'eBay Inc.', null);
INSERT INTO stocks VALUES ('ESRX', 'Express Scripts Holding Company', null);
INSERT INTO stocks VALUES ('EXPD', 'Expeditors International of Washington', null);
INSERT INTO stocks VALUES ('EXPE', ' Expedia Inc.', null);
INSERT INTO stocks VALUES ('FAST', 'Fastenal Company', null);
INSERT INTO stocks VALUES ('FB', 'Facebook Inc.', null);
INSERT INTO stocks VALUES ('FISV', 'Fiserv Inc.', null);
INSERT INTO stocks VALUES ('FOX', 'First Century Fox Inc.', null);
INSERT INTO stocks VALUES ('FOXA', 'Twenty-First Century Fox Inc.', null);
INSERT INTO stocks VALUES ('GILD', 'Gilead Sciences Inc.', null);
INSERT INTO stocks VALUES ('GMCR', 'Keurig Green Mountain Inc.', null);
INSERT INTO stocks VALUES ('GOOG', 'Alphabet Inc.', null);
INSERT INTO stocks VALUES ('GOOGL', 'Alphabet Inc.', null);
INSERT INTO stocks VALUES ('GRMN', 'Garmin Ltd.', null);
INSERT INTO stocks VALUES ('HSIC', 'Henry Schein Inc.', null);
INSERT INTO stocks VALUES ('ILMN', 'Illumina Inc.', null);
INSERT INTO stocks VALUES ('INCY', 'Incyte Corporation', null);
INSERT INTO stocks VALUES ('INTC', 'Intel Corporation', null);
INSERT INTO stocks VALUES ('INTU', 'Intuit Inc.', null);
INSERT INTO stocks VALUES ('ISRG', 'Intuitive Surgical Inc.', null);
INSERT INTO stocks VALUES ('JD', 'JD.com Inc.', null);
INSERT INTO stocks VALUES ('KHC', 'The Kraft Heinz Company', null);
INSERT INTO stocks VALUES ('KLAC', 'KLA-Tencor Corporation', null);
INSERT INTO stocks VALUES ('LBTYA', 'Liberty Global plc', null);
INSERT INTO stocks VALUES ('LBTYK', 'Liberty Global plc', null);
INSERT INTO stocks VALUES ('LILA', 'Liberty Global plc', null);
INSERT INTO stocks VALUES ('LILAK', 'Liberty Global plc', null);
INSERT INTO stocks VALUES ('LLTC', 'Linear Technology Corporation', null);
INSERT INTO stocks VALUES ('LMCA', 'Liberty Media Corporation', null);
INSERT INTO stocks VALUES ('LRCX', 'Lam Research Corporation', null);
INSERT INTO stocks VALUES ('LVNTA', 'Liberty Interactive Corporation', null);
INSERT INTO stocks VALUES ('MAR', 'Marriott International', null);
INSERT INTO stocks VALUES ('MAT', 'Mattel Inc.', null);
INSERT INTO stocks VALUES ('MDLZ', 'Mondelez International Inc.', null);
INSERT INTO stocks VALUES ('MNST', 'Monster Beverage Corporation', null);
INSERT INTO stocks VALUES ('MSFT', 'Microsoft Corporation', null);
INSERT INTO stocks VALUES ('MU', 'Micron Technology', null);
INSERT INTO stocks VALUES ('MYL', 'Mylan N.V.', null);
INSERT INTO stocks VALUES ('NFLX', 'Netflix Inc.', null);
INSERT INTO stocks VALUES ('NTAP', 'NetApp Inc.', null);
INSERT INTO stocks VALUES ('NVDA', 'NVIDIA Corporation', null);
INSERT INTO stocks VALUES ('NXPI', 'NXP Semiconductors N.V.', null);
INSERT INTO stocks VALUES ('ORLY', 'O\'Reilly Automotive Inc.', null);
INSERT INTO stocks VALUES ('PAYX', 'Paychex Inc.', null);
INSERT INTO stocks VALUES ('PCAR', 'PACCAR Inc.', null);
INSERT INTO stocks VALUES ('PCLN', 'The Priceline Group Inc.', null);
INSERT INTO stocks VALUES ('PYPL', 'PayPal Holdings Inc.', null);
INSERT INTO stocks VALUES ('QCOM', 'QUALCOMM Incorporated', null);
INSERT INTO stocks VALUES ('QVCA', 'Liberty Interactive Corporation', null);
INSERT INTO stocks VALUES ('REGN', 'Regeneron Pharmaceuticals Inc.', null);
INSERT INTO stocks VALUES ('ROST', 'Ross Stores Inc.', null);
INSERT INTO stocks VALUES ('SBAC', 'SBA Communications Corporation', null);
INSERT INTO stocks VALUES ('SBUX', 'Starbucks Corporation', null);
INSERT INTO stocks VALUES ('SIRI', 'Sirius XM Holdings Inc.', null);
INSERT INTO stocks VALUES ('SNDK', 'SanDisk Corporation', null);
INSERT INTO stocks VALUES ('SPLS', 'Staples Inc.', null);
INSERT INTO stocks VALUES ('SRCL', 'Stericycle Inc.', null);
INSERT INTO stocks VALUES ('STX', 'Seagate Technology.', null);
INSERT INTO stocks VALUES ('SYMC', 'Symantec Corporation', null);
INSERT INTO stocks VALUES ('SWKS', 'Skyworks Solutions Inc.', null);
INSERT INTO stocks VALUES ('TSCO', 'Tractor Supply Company', null);
INSERT INTO stocks VALUES ('TSLA', 'Tesla Motors Inc.', null);
INSERT INTO stocks VALUES ('TRIP', 'TripAdvisor Inc.', null);
INSERT INTO stocks VALUES ('TXN', 'Texas Instruments Incorporated', null);
INSERT INTO stocks VALUES ('VIAB', 'Viacom Inc.', null);
INSERT INTO stocks VALUES ('VIP', 'VimpelCom Ltd.', null);
INSERT INTO stocks VALUES ('VOD', 'Vodafone Group Plc', null);
INSERT INTO stocks VALUES ('VRSK', 'Verisk Analytics Inc.', null);
INSERT INTO stocks VALUES ('VRTX', 'Vertex Pharmaceuticals Incorporated', null);
INSERT INTO stocks VALUES ('WBA', 'Walgreens Boots Alliance Inc.', null);
INSERT INTO stocks VALUES ('WDC', 'Western Digital Corporation', null);
INSERT INTO stocks VALUES ('WFM', 'Whole Foods Market Inc.', null);
INSERT INTO stocks VALUES ('WYNN', 'Wynn Resorts Limited', null);
INSERT INTO stocks VALUES ('XLNX', 'Xilinx Inc.', null);
INSERT INTO stocks VALUES ('YHOO', 'Yahoo! Inc.', null);


/*ALTER TABLE stocks ADD CONSTRAINT stock_unique UNIQUE (name1);*/
ALTER TABLE stocks ORDER BY name1 ASC;
/*ALTER TABLE users ADD CONSTRAINT username_unique UNIQUE (username);*/

